org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Minecraft
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

# NeoForge
neo_version=21.1.249
neo_version_range=[21.1.233,21.2)
loader_version_range=[1,)

# Xaero
xaero_lib_version=1.1.0

xaero_minimap_version=25.3.13
xaero_minimap_file_id=8046966
xaero_minimap_version_range=[25.3.13,)

xaero_world_map_version=1.40.16
xaero_world_map_file_id=8042208
xaero_world_map_version_range=[1.40.16,)

mod_id=xaero_iconize
mod_name=Xaero Iconize
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=ru.lotuze.xaero_iconize
